### ISSUE TITLE
Arterial blood pressure waveform not correctly synced with ECG tracing

### ISSUE THREAD

**Issue by MASTANAZ** [tanjera/infirmary-integrated#4]
The ventricular ejection upstroke up the arterial blood pressure waveform should not start until after the QRS complex of the ECG tracing; it should start somewhere in the middle of the T-wave up-slope. The arterial blood pressure waveform should be phase shifted by ~200-300ms behind the ECG tracing.

**Current Implementation**
![image](https://user-images.githubusercontent.com/6020179/54402906-566bd880-46a4-11e9-9b4e-a1562ed07906.png)

**Correct Appearance** 
![image](https://user-images.githubusercontent.com/6020179/54402777-b01fd300-46a3-11e9-880d-59a013823f40.png)

**Comment by tanjera** [comment]
Great sample photo.

Also to do: when adjusting the concatenation of the ABP waveform, rework the systolic wave deflection from the peak into the dicrotic notch so it actually looks more like the real-life example.

**Comment by tanjera** [comment]
Fixed timing and wave deflection in latest commit.
https://github.com/tanjera/infirmary-integrated/commit/353e711da2fc90358cdf15e899e516db1a82c25f
