### ISSUE TITLE
Bug: On loading a file in incorrect format, crashes.

### ISSUE THREAD

**Issue by tanjera** [tanjera/infirmary-integrated#81]
Downloaded simulation the wrong way (e.g. view file in internet explorer, copy/paste to text file, give .ii extension); crashed on loading file; did not handle exception.

Replicate in debug mode, trace why program unable to parse file and just crashes. Likely due to file encoding issue.

**Comment by Frogman7** [comment]
I was unable to replicate this issue, can you share a file that would cause this?

**Comment by tanjera** [comment]
Probably, but also worth noting that all of the code that loads and parses files are wrapped in try {} catch {} statements ... if an exception is thrown, it's pretty much muted in catch {} and an error dialog pops up saying something like "unable to load file." So if you're looking for a real crash, you won't see it. Also, it will run the exact same abort routine if the file is in an incorrect format.

With that said, this is more of an edge case, and I don't think people should be surprised when a manually edited file crashes. I'm nearly positive there was just some added UTF encoding characters at the beginning of the file that Infirmary didn't recognize and probably aborted on.

**Comment by tanjera** [comment]
Haha yeah, I just tried to replicate this too, and it worked fine. I think I'll just close it.

Thank you for testing!!
